accounts:
  - name: alice
    coins: ["20000DGZ", "200000000stake"]
  - name: bob
    coins: ["10000DGZ", "100000000stake"]
validator:
  name: alice
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5DGZ", "100000stake"]
build:
  binary: "digzan"  
  ldflags: [ "-X main.Version=production", "-X main.Date=23/03/2022T19:54" ]
